# Generated by Django 5.2.9 on 2025-12-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seolog',
            name='content_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='duplicate_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='google_terms_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seolog',
            name='google_terms_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='h2_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='h3_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='h4_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='h5_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='h6_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='has_favicon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seolog',
            name='has_missing_h1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seolog',
            name='has_missing_meta_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seolog',
            name='has_missing_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seolog',
            name='has_multiple_h1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seolog',
            name='has_short_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seolog',
            name='has_viewport_meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seolog',
            name='images_without_alt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='keyword_density',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seolog',
            name='seo_friendliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='seo_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seolog',
            name='top_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seolog',
            name='total_images',
            field=models.IntegerField(default=0),
        ),
    ]
